#!/bin/sh

set -e

case "$1" in
    configure)
        chmod 755 /usr/share/solr/scripts/*

	update-alternatives --install /etc/solr/home solr-home /etc/solr/home-available/default 990
	update-alternatives --install /etc/solr/home solr-home /etc/solr/home-available/multicore 500

        . /usr/share/debconf/confmodule
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
	exit 1
    ;;
esac

#DEBHELPER#

exit 0
